spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/web_program"
    username: root
    password: 123456789
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
  web:
    locale: vi_VN
server:
  port: 8081


